export const ROUTES = {
  DASHBOARD: "/dashboard",
  LOGIN: "/",
  ORDER_STATUS: "/order-status",
  ORDERS: "/orders",
  PRODUCTS: "/products",
  COUPONS: "/coupons",
  CUSTOMERS: "/customers",
  TAXES: "/taxes",
  SHIPPINGS: "/shippings",
  SETTINGS: "/settings",
  CATEGORIES: "/categories",
  TYPES: "/types",
  PROFILE_UPDATE: "/profile-update",
  LOGOUT: "/logout",
  ATTRIBUTES: "/attributes",
  ATTRIBUTE_VALUES: "/attribute-values",
};
